import { createStore } from "vuex";

export default createStore({
  state: {
    events: [
      {
        id: 1,
        name: 'ARCA Sunday Remedy: Soul Medicine w/ Alexia Glensy',
        city: 'Milano',
        price: 'Gratis',
        date: new Date(new Date().getFullYear(), 9, 8),
        category: 'party',
        at: 'ARCA',
        image: require('@/assets/media/arcasunday.avif'),
      },
      {
        id: 2,
        name: 'Moses Boyd',
        city: 'Milano',
        price: 25,
        date: new Date(2023, 9, 19),
        category: 'Gigs',
        at:'Anfiteatro Martesana',
        image: require('@/assets/media/moses_boyd.avif'),
      },
      {
        id: 3,
        name: 'Disco Stupenda w/ Whodamanny & Tommiboy',
        city: 'Milano',
        price: 25,
        date: 'Gio, 24 Ott',
        category: 'dj',
        image: require('@/assets/media/disco_stupenda.avif'),
      },
      {
        id: 4,
        name: 'Purple Disco Machine',
        city: 'Milano',
        price: 40.25,
        date: '2023-27-10',
        category: 'film',
        image: require('@/assets/media/purple_disco.jpeg'),
      },
      {
        id: 5,
        name: 'Sneakerness Milan Day1',
        city: 'Milano',
        price: 12,
        at: 'East End Studios',
        date: '2023-14-10',
        category: 'social',
        image: require('@/assets/media/sneakerness.avif'),
      },
      {
        id: 6,
        name: 'Pierluca Mariti (Piuttosto_Che) presenta “Niente di che”',
        city: 'Roma',
        price: 26.28,
        date: '2023-24-10',
        category: 'Artist Signing',
        image: '../assets/media/nottelunga.jpeg',
      },
      {
        id: 7,
        name: 'Sneakerness Milan Day2',
        city: 'Milano',
        price: 26.28,
        date: '2023-15-10',
        category: 'film',
        image: require('@/assets/media/sneakerness2.avif'),
      },
      {
        id: 8,
        name: 'Parra for Cuva LIVE',
        city: 'Milano',
        price: 26.28,
        date: '2023-12-10',
        category: 'film',
        image: require('@/assets/media/parraforcura.avif'),
      },
      {
        id: 9,
        name: 'Valerio Vaudano aka Vaudafunk dj set',
        city: 'Milano',
        price: 26.28,
        at: 'Clèr',
        date: '2023-7-10',
        category: 'dj',
        image: require('@/assets/media/valerio.avif'),
      },

      {id: 10,
      name: 'No More what’s next',
      city: 'Milano',
      price: 26.28,
      at: 'Apollo Club Milano',
      date: '2023-7-10',
      category: 'dj',
      image: require('@/assets/media/nomore.avif'),
    },

    {id: 10,
      name: 'Take It Easy: DJ BORING + DJLMP + Ilaria Gr',
      city: 'Milano',
      price: 11.32,
      at: 'Tunnel Club',
      date: '2023-7-10',
      category: 'dj',
      image: require('@/assets/media/takeiteasy.avif'),
    },

    {id: 30,
      name: 'Arto Lindsay - JAZZMI 2023',
      city: 'Milano',
      price: 'gratis',
      at: 'Armani / Silos',
      date: '2023-8-12',
      category: 'gigs',
      image: require('@/assets/media/arto.avif'),
    },

    {id: 31,
      name: 'BABYMETAL UK & EU Tour 2023 + WARGASM ',
      city: 'Milano',
      price: 46,
      at: 'Fabrique',
      date: '2023-8-12',
      category: 'gigs',
      image: require('@/assets/media/babymetal.avif'),
    },

      {
        id: 20,
        name: 'Making the pure Halloween',
        city: 'Philadelphia',
        price: 26.28,
        at:'TRANSCENDENTAL Secret Location',
        date: '2023-12-10',
        category: 'Party',
        image:require('@/assets/media/pure_halloween.avif'),
      },
      {
        id: 21,
        name: 'Pegboy, Flag of Democracy',
        city: 'Philadelphia',
        price: 26.28,
        at:'Ukie Club',
        date: '2023-12-10',
        category: 'gigs',
        image:require('@/assets/media/pegboy.avif'),
      }
    

      
      // Aggiungi altri eventi qui
    ],
  },
  // Mutations, actions e getters qui, se necessario
});

